import type { Product } from './types';

type MockSeed = Omit<Product, 'slug' | 'categoryId' | 'colors' | 'sizes' | 'tags' | 'status' | 'featured' | 'updatedAt' | 'categoryInfo' | 'inStock'>;

const slugify = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

const seeds: MockSeed[] = [
  {
    id: 1,
    name: 'Velora Quantum X1 Pro',
    description: 'The ultimate workstation for creators and developers. Featuring the latest M3 Ultra chip and 128GB unified memory.',
    price: 85000,
    currency: 'EGP',
    category: 'Computers',
    brand: 'Velora',
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 15,
    specifications: { processor: 'M3 Ultra', ram: '128GB', storage: '2TB SSD' },
    rating: 4.9,
    reviewCount: 128,
    discount: 10,
    variants: {
      colors: ['Space Gray', 'Silver', 'Midnight'],
      storage: ['512GB', '1TB', '2TB', '4TB'],
    },
    freeShipping: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'Nebula G-Sync Monitor',
    description: '34-inch curved OLED gaming monitor with 240Hz refresh rate and 0.03ms response time.',
    price: 22000,
    currency: 'EGP',
    category: 'Gaming',
    brand: 'Nebula',
    images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 45,
    specifications: { size: '34"', panel: 'OLED', refresh: '240Hz' },
    rating: 4.8,
    reviewCount: 342,
    discount: 15,
    freeShipping: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'Titan H1 Wireless Headphones',
    description: 'Active noise cancelling headphones with 60-hour battery life and spatial audio support.',
    price: 12500,
    currency: 'EGP',
    category: 'Accessories',
    brand: 'Titan',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 120,
    specifications: { battery: '60h', connection: 'Bluetooth 5.3', noise: 'ANC' },
    rating: 4.7,
    reviewCount: 856,
    discount: 0,
    variants: {
      colors: ['Obsidian', 'Snow', 'Sand'],
    },
    freeShipping: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    name: 'Aura Smart Home Hub',
    description: 'Centralized control for all your smart devices with built-in AI assistant and privacy-first design.',
    price: 4500,
    currency: 'EGP',
    category: 'Smart Home',
    brand: 'Aura',
    images: ['https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 80,
    specifications: { protocol: 'Matter/Thread', voice: 'Aura AI', privacy: 'Local' },
    rating: 4.6,
    reviewCount: 215,
    discount: 5,
    freeShipping: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    name: 'Zenith Watch Series 9',
    description: 'Premium smartwatch with advanced health tracking, satellite connectivity, and titanium build.',
    price: 18000,
    currency: 'EGP',
    category: 'Wearables',
    brand: 'Zenith',
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30e?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 30,
    specifications: { material: 'Titanium', water: '100m', battery: '72h' },
    rating: 4.9,
    reviewCount: 56,
    discount: 0,
    variants: {
      colors: ['Titanium Gray', 'Ocean Blue', 'Starlight'],
    },
    freeShipping: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 6,
    name: 'Apex Mechanical Keyboard',
    description: 'Customizable mechanical keyboard with hot-swappable switches and PBT keycaps.',
    price: 3200,
    currency: 'EGP',
    category: 'Accessories',
    brand: 'Apex',
    images: ['https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 200,
    specifications: { switches: 'Linear', layout: '75%', rgb: 'Per-key' },
    rating: 4.8,
    reviewCount: 1204,
    discount: 20,
    variants: {
      connectivity: ['Wired', 'Wireless', 'Bluetooth'],
    },
    freeShipping: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 7,
    name: 'Pharos VR Headset',
    description: 'Next-gen standalone VR headset with 4K per eye resolution and full body tracking.',
    price: 35000,
    currency: 'EGP',
    category: 'Gaming',
    brand: 'Pharos',
    images: ['https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 12,
    specifications: { resolution: '8K Total', tracking: 'Inside-out', battery: '4h' },
    rating: 4.9,
    reviewCount: 89,
    discount: 0,
    freeShipping: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 8,
    name: 'Volt S24 Ultra',
    description: 'The most powerful smartphone with integrated AI, 200MP camera, and titanium frame.',
    price: 65000,
    currency: 'EGP',
    category: 'Mobiles',
    brand: 'Volt',
    images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 50,
    specifications: { screen: '6.8" AMOLED', camera: '200MP', chip: 'Snapdragon 8 Gen 3' },
    rating: 4.8,
    reviewCount: 450,
    discount: 5,
    variants: {
      colors: ['Titanium Black', 'Titanium Gray', 'Titanium Violet'],
      storage: ['256GB', '512GB', '1TB'],
    },
    freeShipping: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 9,
    name: 'LumaPad Creator 14',
    description: 'Ultra-thin OLED laptop built for designers with pen-ready touch support and silent cooling.',
    price: 54000,
    currency: 'EGP',
    category: 'Computers',
    brand: 'Luma',
    images: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 18,
    specifications: { display: '14-inch OLED', processor: 'Ryzen AI 9', ram: '32GB' },
    rating: 4.8,
    reviewCount: 188,
    discount: 12,
    variants: {
      colors: ['Graphite', 'Pearl'],
      storage: ['1TB', '2TB'],
    },
    freeShipping: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 10,
    name: 'Nova Buds Elite',
    description: 'Hi-res wireless earbuds with adaptive ANC, spatial audio, and all-day comfort fit.',
    price: 6900,
    currency: 'EGP',
    category: 'Accessories',
    brand: 'Nova',
    images: ['https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 140,
    specifications: { battery: '36h', connection: 'Bluetooth 5.4', codec: 'Hi-Res' },
    rating: 4.7,
    reviewCount: 620,
    discount: 18,
    variants: {
      colors: ['Onyx', 'Cloud', 'Mint'],
    },
    freeShipping: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 11,
    name: 'Orbit Tablet Air',
    description: 'Powerful 13-inch tablet with desktop mode, stylus support, and day-long battery life.',
    price: 28500,
    currency: 'EGP',
    category: 'Mobiles',
    brand: 'Orbit',
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 34,
    specifications: { display: '13-inch 120Hz', chip: 'Orbit Neural X', battery: '14h' },
    rating: 4.8,
    reviewCount: 274,
    discount: 10,
    variants: {
      colors: ['Silver', 'Blue'],
      storage: ['256GB', '512GB', '1TB'],
    },
    freeShipping: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 12,
    name: 'EchoBeam Smart Projector',
    description: 'Laser projector with smart TV system, Dolby Atmos output, and instant auto focus.',
    price: 31900,
    currency: 'EGP',
    category: 'Smart Home',
    brand: 'EchoBeam',
    images: ['https://images.unsplash.com/photo-1546538915-a9e2c8d6a2f7?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 11,
    specifications: { brightness: '2500 ANSI', resolution: '4K', smart: 'Google TV' },
    rating: 4.9,
    reviewCount: 92,
    discount: 14,
    freeShipping: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 13,
    name: 'PulseCam 360 Security Kit',
    description: 'AI-powered home security bundle with panoramic view, motion alerts, and local backup.',
    price: 11900,
    currency: 'EGP',
    category: 'Smart Home',
    brand: 'Pulse',
    images: ['https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 29,
    specifications: { camera: '4K 360', storage: 'Local + Cloud', ai: 'Object detection' },
    rating: 4.6,
    reviewCount: 208,
    discount: 9,
    freeShipping: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 14,
    name: 'Helix Router Pro 7',
    description: 'Tri-band Wi-Fi 7 mesh router with gamer priority mode and smart home traffic control.',
    price: 9700,
    currency: 'EGP',
    category: 'Accessories',
    brand: 'Helix',
    images: ['https://images.unsplash.com/photo-1649972904349-6e44c42644a7?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 47,
    specifications: { connection: 'Wi-Fi 7', coverage: '350 sqm', speed: '11 Gbps' },
    rating: 4.8,
    reviewCount: 301,
    discount: 16,
    freeShipping: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 15,
    name: 'Core Mini Station',
    description: 'Compact AI mini PC with desktop-class ports, whisper-quiet thermals, and dual display output.',
    price: 22400,
    currency: 'EGP',
    category: 'Computers',
    brand: 'Core',
    images: ['https://images.unsplash.com/photo-1587202372775-e229f172b9d7?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 26,
    specifications: { processor: 'Core Ultra 9', ram: '32GB', storage: '1TB SSD' },
    rating: 4.7,
    reviewCount: 149,
    discount: 8,
    variants: {
      colors: ['Black'],
      storage: ['1TB', '2TB'],
    },
    freeShipping: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 16,
    name: 'SonicBar Atmos Max',
    description: 'Immersive cinematic soundbar with wireless subwoofer and room calibration.',
    price: 15800,
    currency: 'EGP',
    category: 'Accessories',
    brand: 'SonicBar',
    images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 41,
    specifications: { audio: 'Dolby Atmos', channels: '7.1.2', connection: 'Wi-Fi + HDMI eARC' },
    rating: 4.8,
    reviewCount: 233,
    discount: 20,
    freeShipping: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 17,
    name: 'Rift One Console',
    description: 'Next-generation gaming console with 4K 120fps support, instant resume, and cloud sync.',
    price: 26900,
    currency: 'EGP',
    category: 'Gaming',
    brand: 'Rift',
    images: ['https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 22,
    specifications: { gpu: 'Custom RDNA', storage: '1TB NVMe', connectivity: 'Wi-Fi 6E' },
    rating: 4.9,
    reviewCount: 410,
    discount: 7,
    freeShipping: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 18,
    name: 'Ember Ring Sleep Tracker',
    description: 'Minimal smart ring with continuous health insights, sleep scoring, and long battery life.',
    price: 13500,
    currency: 'EGP',
    category: 'Wearables',
    brand: 'Ember',
    images: ['https://images.unsplash.com/photo-1617038260897-41a1f14a8ca6?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 58,
    specifications: { battery: '7 days', material: 'Titanium', sensors: 'Sleep + HRV' },
    rating: 4.6,
    reviewCount: 176,
    discount: 11,
    variants: {
      colors: ['Matte Black', 'Silver', 'Rose'],
      storage: ['Size 7', 'Size 9', 'Size 11'],
    },
    freeShipping: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 19,
    name: 'Flux Portable SSD 4TB',
    description: 'Pocket-sized NVMe SSD with creator-grade speeds and rugged drop-resistant shell.',
    price: 7600,
    currency: 'EGP',
    category: 'Accessories',
    brand: 'Flux',
    images: ['https://images.unsplash.com/photo-1591488320449-011701bb6704?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 160,
    specifications: { speed: '2000MB/s', capacity: '4TB', build: 'IP55' },
    rating: 4.7,
    reviewCount: 517,
    discount: 13,
    freeShipping: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 20,
    name: 'Atlas Vision Drone',
    description: 'Foldable 8K drone with obstacle avoidance, cinematic stabilization, and AI flight modes.',
    price: 39900,
    currency: 'EGP',
    category: 'Gaming',
    brand: 'Atlas',
    images: ['https://images.unsplash.com/photo-1473968512647-3e447244af8f?q=80&w=1000&auto=format&fit=cover'],
    vendorId: 2,
    stock: 9,
    specifications: { camera: '8K', battery: '42 min', smart: 'AI follow' },
    rating: 4.9,
    reviewCount: 88,
    discount: 6,
    freeShipping: true,
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_PRODUCTS: Product[] = seeds.map((product, index) => ({
  ...product,
  slug: slugify(product.name),
  categoryId: 0,
  colors: product.variants?.colors || [],
  sizes: product.variants?.storage || [],
  tags: [product.category.toLowerCase().replace(/\s+/g, '-'), product.brand.toLowerCase()],
  status: 'active',
  featured: index < 6,
  inStock: product.stock > 0,
  updatedAt: product.createdAt,
}));
